server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AndrePxd/server-config.git
          ignoreLocalSshSettings: true
          hostKey: AAAAB3NzaC1yc2EAAAADAQABAAABgQCs8hr9NAhcscpvvx8b2AdV1jncXhOW0Lhe56C6pag0yFOnl3l8A8KT/9naJR0KshoflVmhz5NOh2RSB7+SI8VEjceEtVlsVxGZRsshz4a8dcEAWnGIFvV9fvV8N8jRILVvApHW+BhcYVNGPqGSMs0T86SI8A08Oe9FqeUdEeHGZl3omVZ7pDz0OO9Ug4Xf3UV+8Z2xtj1XcoE442RctDyIxc3fljpVmHnm9GKl86GJh+RohFrlxS6NX6x7TrBTegI9vW7x+prlAmf0dM/Dd2Jdec0/S4hakerL++NOOj5HGB37BwOY4dLGUesN+3d8oF7uj3OX/yoO18DepKnhUJpX1zApr6giTiDxC9UHRpnUpL37FRWmESMJgN9rM3X21wEYVDFvyrOfh9E6SOThJJb57OLfSOKxH4bkujYvH/rUAbipBqRm1pAXRyxTxk9z/CSIIibO2ZQkt5wdsO2+KTwryw9rOb4y0zFq+FwTJa/9cgRBOLLcQO3hu+N27kaZURk= andre@DESKTOP-PG19R0H
          hostKeyAlgorithm: shh-rsa
          privateKey: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
            NhAAAAAwEAAQAAAYEArPIa/TQIXLHKb78fG9gHVdY53F4TltC4XueguqWoNMhTp5d5fAPC
            k//Z2iUdCrIaH5VZoc+TTodkUge/kiPFRI3HhLVZbFcRmUbLIc+GvHXBAFpxiBb1fX71fD
            fI0SC1bwKR1vgYXGFTRj6hkjLNE/OkiPANPDnvRanlHRHhxmZd6JlWe6Q89DjvVIOF391F
            fvGdsbY9V3KBOONkXLQ8iMXN35Y6VZh55vRipfOhiYfkaIRa5cUujV+se06wU3oCPb1u8f
            qa5QJn9HTPw3diXXnNP0uIWpHqy/vjTjo+Rxgd+wcDmOHSxlHrDft3fKBe7o9zl/8qDtfA
            3qSp4VCaV9cwKa+oIk4g8QvVB0aZ1KS9+xUVphEjCYDfazN19tcBGFQxb8qzn4fROkjk4S
            SW+ezi30jisR+G5Lo2Lx/61AG4qQakZtaQF0csU8ZPc/wkiCImztmUJLecHbDtvik8K8sP
            azm+MtMxavhcEyWv/XIEQTiy3EDt4bvjdu5GmVEZAAAFkHg7TgV4O04FAAAAB3NzaC1yc2
            EAAAGBAKzyGv00CFyxym+/HxvYB1XWOdxeE5bQuF7noLqlqDTIU6eXeXwDwpP/2dolHQqy
            Gh+VWaHPk06HZFIHv5IjxUSNx4S1WWxXEZlGyyHPhrx1wQBacYgW9X1+9Xw3yNEgtW8Ckd
            b4GFxhU0Y+oZIyzRPzpIjwDTw570Wp5R0R4cZmXeiZVnukPPQ471SDhd/dRX7xnbG2PVdy
            gTjjZFy0PIjFzd+WOlWYeeb0YqXzoYmH5GiEWuXFLo1frHtOsFN6Aj29bvH6muUCZ/R0z8
            N3Yl15zT9LiFqR6sv74046PkcYHfsHA5jh0sZR6w37d3ygXu6Pc5f/Kg7XwN6kqeFQmlfX
            MCmvqCJOIPEL1QdGmdSkvfsVFaYRIwmA32szdfbXARhUMW/Ks5+H0TpI5OEklvns4t9I4r
            EfhuS6Ni8f+tQBuKkGpGbWkBdHLFPGT3P8JIgiJs7ZlCS3nB2w7b4pPCvLD2s5vjLTMWr4
            XBMlr/1yBEE4stxA7eG743buRplRGQAAAAMBAAEAAAGBAI41Me4cV/folb4XWLwrgbSaR8
            +lZ9QuYjxfmDGBv/NO+kKnclSAPwI1cmxG8j92PbbUtvQv3D/JYrt09Zh0Y2RAdNvxxsso
            OSdhJ+zwWSkkZoQk2o/92PTNbYwrzqvvimDyqvsp29YyjSgInhC6Rxlt0VBsm2V3egE9d1
            DVAGKEkBmP5KYcYaasHlfPIkj3CIsen/2eDYiXdhxSFpeH+PK6O9PrEqKJk0tOjsNItv6A
            yFcM5jVjUykaj5iBFso9Wrnb9CD1xXiipJyO9ANN/zzeuOCi/5BXu67AAAWeEbG+QElCOo
            v/zgDwzhqWGGCtoLVDChQwbWYAmhmRArczimO7IfB0SBu2Juq98aw+cZcSdtmlBIJT0sKr
            k5BXkogc4dyBE6EovdSbpvj44fLvhAeC3YQML2w7j1KC1e+UEXU8ab9swHoKJkXQ+i4N45
            c/7mxo47J2aFZKUYjNaJSym6mPo/RDWevlSayOGPyjmMH1jLXTx6/Y8j4ZXBsNJ90dJQAA
            AMEA17zEtKQ1vY+oon4muPTAgMhXiO7t+lytf4plVe5xSa7s2X6RxpxinIf/SimfCCLU2Z
            5gowTdVm8BxyrS1Bi13TotzRyVnWDepX96/qPVRrhd/4+KBEaoRvZ9i+t7sPJe71A8Ugr6
            afi7mtY61/xZE6fDuehlr0mjCbi36zNhYYAfc+jRljGcwxh8TAX9eKdkPysxcD7rW4D6fq
            np+9iXUvd9BnThIFWZKwNG7r6YARezBJZmd6rSSm5nfi3aX0YaAAAAwQDeTXaah0LWq342
            tUryJLE47XzMOYvBMQApa9Lr6rYQt+45cZkz+5LQ0Kw+NEb/CZpmdsXB+mjQcXKGPlnTYx
            GhwUV4Hvjl7a2M8Mk1TGxBeS4hjEHnfKfwxb0kiVXBOHrK3gN45Coouug3ub2Yrc1f7ML+
            cDW9qo4MBfHsuG/vr83sDsKd9QlHIA9H8TRCLUjf+n6G9oHDrJJnT2ZVDugLV4YWGVXHfF
            A4osBDv1h6BfT/WGrYZMouUz87BB0zo8sAAADBAMcpVILmL3YEzKS11G9WyzgLW7TcUIZS
            qP/uQhN9Zsd8JKRv1dSbGzhE9hMk4QoZcCJ5i4Rr5lkQcK5g58GMSwn2er/6Jw7Rc+oCQY
            1jjy0jd6je9TNcL9sSlICYqKesErw14X1coT0ablIKZDWLmEqLRX5D67eqybO/zbG99qy2
            D/uezkLXrC5ExCF/yfD2DlagECr+cfXvYtYJ4pJ/c2/BO7ge9UZ+Uz4lLyTCQyLEUOmK+V
            ps5XzsHszFR3iqKwAAABVhbmRyZUBERVNLVE9QLVBHMTlSMEgBAgME
            -----END OPENSSH PRIVATE KEY-----
  application:
    name: ms-config-server
encrypt:
  key: /3(v*a!#z^#gzJ)Ql[(:rCsiqD~+F3XhIBQ/xBHZ0P$EzTv[la